---
baseURL: http://example.org/
languageCode: en-us
title: System Administrator Portfolio
module:
  imports:
  - path: github.com/theNewDynamic/gohugo-theme-ananke
DefaultContentLanguage: ru
SectionPagesMenu: main
Paginate: 3
googleAnalytics: ''
enableRobotsTXT: true
sitemap:
  changefreq: monthly
  priority: 0.5
  filename: sitemap.xml
params:
  favicon: ''
  site_logo: ''
  description: System Administrator Portfolio Site
  facebook: ''
  twitter: ''
  instagram: ''
  youtube: ''
  github: ''
  gitlab: ''
  linkedin: ''
  mastodon: ''
  slack: ''
  stackoverflow: ''
  rss: ''
  background_color_class: bg-black
  featured_image: "/images/gohugo-default-sample-hero-image.jpg"
  recent_posts_number: 2
